version: '3.8'
services:
  bookstore:
    image: bookstore
    depends_on:
      bookstore-postgresql:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookstore-postgresql:5432/bookstore
    ports:
      - "8080:8080"
  bookstore-postgresql:
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "bookstore" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - POSTGRES_USER=bookstore
      - POSTGRES_PASSWORD=bookstore
    ports:
      - "5432:5432"