version: '3.8'
services:
  bookstore:
    image: resource
    env_file:
      - .env
    depends_on:
      bookstore-postgresql:
        condition: service_healthy
      bookstore-discovery:
        condition: service_healthy
      bookstore-auth:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${RESOURCE_PORT}/actuator/health | grep UP || exit -1" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bookstore-postgresql:${DB_PORT}/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    ports:
      - "8081:${RESOURCE_PORT}" # todo dont expose on production
  bookstore-postgresql:
    image: postgres:latest
    env_file:
      - .env
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", $DB_NAME, "-U", $DB_USERNAME]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:${DB_PORT}"
  bookstore-discovery:
    image: discovery:latest
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${DISCOVERY_PORT}/actuator/health | grep UP || exit -1" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - "8761:${DISCOVERY_PORT}"
  bookstore-gateway:
    image: gateway:latest
    env_file:
      - .env
    depends_on:
      bookstore-discovery:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${GATEWAY_PORT}/actuator/health | grep UP || exit -1" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - "8080:${GATEWAY_PORT}"
  bookstore-auth:
    image: auth:latest
    env_file:
      - .env
    depends_on:
      bookstore-discovery:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:${AUTH_SERVER_PORT}/actuator/health | grep UP || exit -1" ]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    ports:
      - "8082:${AUTH_SERVER_PORT}"  # todo dont expose on production