server:
  port: ${RESOURCE_PORT:8081}
spring:
  application:
    name: bookstore
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:bookstore}
    username: ${DB_USERNAME:bookstore}
    password: ${DB_PASSWORD:bookstore}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # development only
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://auth"
management:
  metrics:
    enabled: false
  endpoints:
    web:
      discovery:
        enabled: false
      exposure:
        include: [ 'health', 'info' ]
eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE:http://client:client@localhost:8761/eureka}
  instance:
    preferIpAddress: true