server:
  port: ${RESOURCE_PORT:8081}
spring:
  application:
    name: bookstore-resource
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:bookstore}
    username: ${DB_USERNAME:bookstore}
    password: ${DB_PASSWORD:bookstore}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # development only
management:
  metrics:
    enabled: false
  endpoints:
    web:
      discovery:
        enabled: false
      exposure:
        include: [ 'health', 'info' ]
eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE:localhost}:${DISCOVERY_PORT:8761}/eureka
  instance:
    preferIpAddress: true