server:
  port: ${AUTH_SERVER_PORT:8082}
spring:
  application:
    name: auth
  security:
    oauth2:
      authorizationserver:
        client:
          bookstore-gateway:
            registration:
              client-id: "${GATEWAY_CLIENT_ID:gateway}"
              client-secret: "${GATEWAY_CLIENT_SECRET:{noop}gateway}"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "client_credentials"
              scopes:
                - "read"
                - "write"
management:
  metrics:
    enabled: false
  endpoints:
    web:
      discovery:
        enabled: true
      exposure:
        include: [ 'health', 'info' ]
eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVICE:localhost}:${DISCOVERY_PORT:8761}/eureka
  instance:
    preferIpAddress: true